requires = ["tox>=4"]
env_list = ["pytest", "unittest"]

[env.pytest]
description = "pytest"
deps = ["pytest", "-r requirements.txt"]
commands = [["python", "-m", "pytest", "tests/integration/test_diffusion2d.py"]]

[env.unittest]
description = "unittest"
deps = ["-r requirements.txt"]
commands = [["python", "-m", "unittest", "tests/unit/test_diffusion2d_functions.py"]]